### ISSUE TITLE
MVP 0.2

### ISSUE THREAD

**Issue by mihok** [minimalchat/client#20]
The focus for v0.2 is around moving to a more minimal framework library `s/React/Preact/`. As well as building out notification for connection issues and when the operator is typing. 0.2 is a push to get "Open Source ready" and to release as a Show HN.

# Milestones

- [x]  Convert from React to [Preact](https://github.com/developit/preact) (#23)
- [x] Show '_____ is typing...' (#15)
- [x] Notification bar for connection issues (#16):
   - [x] "Disconnected"
   - [x] "Reconnecting..."
   - [x] "Reconnected!"
   - [x] "Connection failed, [retry](#)" (after 10 reconnection attempts)
- [x] Start in closed state (#19)
- [x] Recall previous sessions (#31)
- [x] Create `CONTRIBUTING.md` file (#14)
- [x] Create Issue template (#30)

**Comment by mihok** [comment]
Idea's:

- [ ]  Convert from React to [Preact](https://github.com/developit/preact)
- [ ] Show '_____ is typing...'
- [ ] Notification bar for connection issues:
   - [ ] Disconnected
   - [ ] Reconnecting...
   - [ ] Reconnected!
   - [ ] Connection failed, [reload](#) (after 10 reconnection attempts)

**Comment by mihok** [comment]
Done.
