### ISSUE TITLE
MVP 0.3

### ISSUE THREAD

**Issue by mihok** [minimalchat/client#43]
The focus for 0.3 is around getting things set up for the Chat as a Service

# Milestones

- [ ] Update client's alternate themes (`FLOAT`, `SIDEPANEL`) to be up to date with `MESSENGER` theme
- [ ] Think about how to deploy script after client signs up
- [ ] Think about how customization and theme editor will work

**Comment by broneks** [comment]
> Think about how to deploy script after client signs up

I think a user would have some sort of "public DSN" (https://en.wikipedia.org/wiki/Data_source_name) that links their client with their operator and daemon.

An example: 
`{PROTOCOL}://{PUBLIC_KEY}@{HOST}/{PATH}{PROJECT_ID}'
`'https://*****@minimal.chat/<project>'`

Unless of course they are hosting it themselves.

>  Think about how customization and theme editor will work
This doesn't sound truly minimal. But we could have settings (maybe via operator or a config in the client script) that position it on the screen and give it a certain header colour. Besides that a client could override the styles themselves with their own stylesheet.

**Comment by mihok** [comment]
Both points are more geared to the commercialization, so its going to be a bit unique. The dashboard that the client logs into will have the theme editor. Our implementation doesn't need to be "minimal".  It _must_ be able to be customizable otherwise we may take away from client website branding, the minimal value is appealing here because we want to have a minimal effect on the presentation and therefore need to blend into the client website as they see fit.
